use crate::cpu::cpu::Opcode;
use crate::cpu::registers::{Registers8, Registers16};

pub enum Instructions {
    NONE,
    PREFIX,
    // Load
    LD_r8_r8(Registers8, Registers8),
    LD_r8_n8(Registers8),
    LD_r16_r16(Registers16, Registers16),
    LD_r16_n16(Registers16),
    LD_HL_r8(Registers8),
    LD_HL_n8,
    LD_r8_HL(Registers8),
    LD_r16_A(Registers16),
    LD_n16_A,
    LDH_n16_A,
    LDH_C_A,
    LD_A_r16(Registers16),
    LD_A_n16,
    LDH_A_n16,
    LDH_A_C,
    LD_HLI_A,
    LD_HLD_A,
    LD_A_HLI,
    LD_A_HLD,
    // 8-bit arithmetic
    ADC_A_r8(Registers8),
    ADC_A_HL,
    ADC_A_n8,
    ADD_A_r8(Registers8),
    ADD_A_HL,
    ADD_A_n8,
    CP_A_r8(Registers8),
    CP_A_HL,
    CP_A_n8,
    DEC_r8(Registers8),
    DEC_HL,
    INC_r8(Registers8),
    INC_HL,
    SBC_A_r8(Registers8),
    SBC_A_HL,
    SBC_A_n8,
    SUB_A_r8(Registers8),
    SUB_A_HL,
    SUB_A_n8,
    // 16-bit arithmetic
    ADD_HL_r16(Registers16),
    DEC_r16(Registers16),
    INC_r16(Registers16),
    // Bitwise logic
    AND_A_r8(Registers8),
    AND_A_HL,
    AND_A_n8,
    CPL,
    OR_A_r8(Registers8),
    OR_A_HL,
    OR_A_n8,
    XOR_A_r8(Registers8),
    XOR_A_HL,
    XOR_A_n8,
    // Bit flag
    BIT_u3_r8(Registers8),
    BIT_u3_HL,
    RES_u3_r8(Registers8),
    RES_u3_HL,
    SET_u3_r8(Registers8),
    SET_u3_HL,
    // Bit shift
    RL_r8(Registers8),
    RL_HL,
    RLA,
    RLC_r8(Registers8),
    RLC_HL,
    RLCA,
    RR_r8(Registers8),
    RR_HL,
    RRA,
    RRC_r8(Registers8),
    RRC_HL,
    RRCA,
    SLA_r8(Registers8),
    SLA_HL,
    SRA_r8(Registers8),
    SRA_HL,
    SRL_r8(Registers8),
    SRL_HL,
    SWAP_r8(Registers8),
    SWAP_HL,
    // Jump and subroutine
    CALL_n16,
    CALL_cc_n16,
    JP_HL,
    JP_n16,
    JP_cc_n16,
    JR_n16,
    JR_cc_n16,
    RET_cc,
    RET,
    RETI,
    RST_vec,
    // Carry flag
    CCF,
    SCF,
    // Stack manipulation
    ADD_HL_SP,
    ADD_SP_e8,
    DEC_SP,
    INC_SP,
    LD_SP_n16,
    LD_n16_SP,
    LD_HL_SP_plus_e8,
    LD_SP_HL,
    POP_AF,
    POP_r16(Registers16),
    PUSH_AF,
    PUSH_r16(Registers16),
    // Interrupt-related
    DI,
    EI,
    HALT,
    // Miscellaneous
    DAA,
    NOP,
    STOP,
}

impl Instructions {
    pub fn get_instruction(opcode: Opcode) -> Instructions {
        match opcode {
            0x00 => Instructions::NOP,
            0x01 => Instructions::LD_r8_r8(Registers8::B, Registers8::C),
            0x02 => Instructions::LD_r16_A(Registers16::BC),
            0x03 => Instructions::INC_r16(Registers16::BC),
            0x04 => Instructions::INC_r8(Registers8::B),
            0x05 => Instructions::DEC_r8(Registers8::B),
            0x06 => Instructions::LD_r8_n8(Registers8::B),
            0x07 => Instructions::RLCA,
            0x08 => Instructions::LD_n16_A,
            0x09 => Instructions::ADD_HL_r16(Registers16::BC),
            0x0A => Instructions::LD_A_r16(Registers16::BC),
            0x0B => Instructions::DEC_r16(Registers16::BC),
            0x0C => Instructions::INC_r8(Registers8::C),
            0x0D => Instructions::DEC_r8(Registers8::C),
            0x0E => Instructions::LD_r8_n8(Registers8::C),
            0x0F => Instructions::RRCA,
            0x10 => Instructions::STOP,
            0x11 => Instructions::LD_r16_n16(Registers16::DE),
            0x12 => Instructions::LD_r16_A(Registers16::DE),
            0x13 => Instructions::INC_r16(Registers16::DE),
            0x14 => Instructions::INC_r8(Registers8::D),
            0x15 => Instructions::DEC_r8(Registers8::D),
            0x16 => Instructions::LD_r8_n8(Registers8::D),
            0x17 => Instructions::RLA,
            0x18 => Instructions::JR_n16,
            0x19 => Instructions::ADD_HL_r16(Registers16::DE),
            0x1A => Instructions::LD_A_r16(Registers16::DE),
            0x1B => Instructions::DEC_r16(Registers16::DE),
            0x1C => Instructions::INC_r8(Registers8::E),
            0x1D => Instructions::DEC_r8(Registers8::E),
            0x1E => Instructions::LD_r8_n8(Registers8::E),
            0x1F => Instructions::RRA,
            0x20 => Instructions::JR_cc_n16,
            0x21 => Instructions::LD_r16_n16(Registers16::HL),
            0x22 => Instructions::LD_HLI_A,
            0x23 => Instructions::INC_r16(Registers16::HL),
            0x24 => Instructions::INC_r8(Registers8::H),
            0x25 => Instructions::DEC_r8(Registers8::H),
            0x26 => Instructions::LD_r8_n8(Registers8::H),
            0x27 => Instructions::DAA,
            0x28 => Instructions::JR_cc_n16,
            0x29 => Instructions::ADD_HL_r16(Registers16::HL),
            0x2A => Instructions::LD_A_HLI,
            0x2B => Instructions::DEC_r16(Registers16::HL),
            0x2C => Instructions::INC_r8(Registers8::L),
            0x2D => Instructions::DEC_r8(Registers8::L),
            0x2E => Instructions::LD_r8_n8(Registers8::L),
            0x2F => Instructions::CPL,
            0x30 => Instructions::JR_cc_n16,
            0x31 => Instructions::LD_r16_n16(Registers16::SP),
            0x32 => Instructions::LD_HLD_A,
            0x33 => Instructions::INC_r16(Registers16::SP),
            0x34 => Instructions::INC_HL,
            0x35 => Instructions::DEC_HL,
            0x36 => Instructions::LD_HL_n8,
            0x37 => Instructions::SCF,
            0x38 => Instructions::JR_cc_n16,
            0x39 => Instructions::ADD_HL_r16(Registers16::SP),
            0x3A => Instructions::LD_A_HLD,
            0x3B => Instructions::DEC_r16(Registers16::SP),
            0x3C => Instructions::INC_r8(Registers8::A),
            0x3D => Instructions::DEC_r8(Registers8::A),
            0x3E => Instructions::LD_r8_n8(Registers8::A),
            0x3F => Instructions::CCF,
            0x40 => Instructions::LD_r8_r8(Registers8::B, Registers8::B),
            0x41 => Instructions::LD_r8_r8(Registers8::B, Registers8::C),
            0x42 => Instructions::LD_r8_r8(Registers8::B, Registers8::D),
            0x43 => Instructions::LD_r8_r8(Registers8::B, Registers8::E),
            0x44 => Instructions::LD_r8_r8(Registers8::B, Registers8::H),
            0x45 => Instructions::LD_r8_r8(Registers8::B, Registers8::L),
            0x46 => Instructions::LD_r8_HL(Registers8::B),
            0x47 => Instructions::LD_r8_r8(Registers8::B, Registers8::A),
            0x48 => Instructions::LD_r8_r8(Registers8::C, Registers8::B),
            0x49 => Instructions::LD_r8_r8(Registers8::C, Registers8::C),
            0x4A => Instructions::LD_r8_r8(Registers8::C, Registers8::D),
            0x4B => Instructions::LD_r8_r8(Registers8::C, Registers8::E),
            0x4C => Instructions::LD_r8_r8(Registers8::C, Registers8::H),
            0x4D => Instructions::LD_r8_r8(Registers8::C, Registers8::L),
            0x4E => Instructions::LD_r8_HL(Registers8::C),
            0x4F => Instructions::LD_r8_r8(Registers8::C, Registers8::A),
            0x50 => Instructions::LD_r8_r8(Registers8::D, Registers8::B),
            0x51 => Instructions::LD_r8_r8(Registers8::D, Registers8::C),
            0x52 => Instructions::LD_r8_r8(Registers8::D, Registers8::D),
            0x53 => Instructions::LD_r8_r8(Registers8::D, Registers8::E),
            0x54 => Instructions::LD_r8_r8(Registers8::D, Registers8::H),
            0x55 => Instructions::LD_r8_r8(Registers8::D, Registers8::L),
            0x56 => Instructions::LD_r8_HL(Registers8::D),
            0x57 => Instructions::LD_r8_r8(Registers8::D, Registers8::A),
            0x58 => Instructions::LD_r8_r8(Registers8::E, Registers8::B),
            0x59 => Instructions::LD_r8_r8(Registers8::E, Registers8::C),
            0x5A => Instructions::LD_r8_r8(Registers8::E, Registers8::D),
            0x5B => Instructions::LD_r8_r8(Registers8::E, Registers8::E),
            0x5C => Instructions::LD_r8_r8(Registers8::E, Registers8::H),
            0x5D => Instructions::LD_r8_r8(Registers8::E, Registers8::L),
            0x5E => Instructions::LD_r8_HL(Registers8::E),
            0x5F => Instructions::LD_r8_r8(Registers8::E, Registers8::A),
            0x60 => Instructions::LD_r8_r8(Registers8::H, Registers8::B),
            0x61 => Instructions::LD_r8_r8(Registers8::H, Registers8::C),
            0x62 => Instructions::LD_r8_r8(Registers8::H, Registers8::D),
            0x63 => Instructions::LD_r8_r8(Registers8::H, Registers8::E),
            0x64 => Instructions::LD_r8_r8(Registers8::H, Registers8::H),
            0x65 => Instructions::LD_r8_r8(Registers8::H, Registers8::L),
            0x66 => Instructions::LD_r8_HL(Registers8::H),
            0x67 => Instructions::LD_r8_r8(Registers8::H, Registers8::A),
            0x68 => Instructions::LD_r8_r8(Registers8::L, Registers8::B),
            0x69 => Instructions::LD_r8_r8(Registers8::L, Registers8::C),
            0x6A => Instructions::LD_r8_r8(Registers8::L, Registers8::D),
            0x6B => Instructions::LD_r8_r8(Registers8::L, Registers8::E),
            0x6C => Instructions::LD_r8_r8(Registers8::L, Registers8::H),
            0x6D => Instructions::LD_r8_r8(Registers8::L, Registers8::L),
            0x6E => Instructions::LD_r8_HL(Registers8::L),
            0x6F => Instructions::LD_r8_r8(Registers8::L, Registers8::A),
            0x70 => Instructions::LD_HL_r8(Registers8::B),
            0x71 => Instructions::LD_HL_r8(Registers8::C),
            0x72 => Instructions::LD_HL_r8(Registers8::D),
            0x73 => Instructions::LD_HL_r8(Registers8::E),
            0x74 => Instructions::LD_HL_r8(Registers8::H),
            0x75 => Instructions::LD_HL_r8(Registers8::L),
            0x76 => Instructions::HALT,
            0x77 => Instructions::LD_HL_r8(Registers8::A),
            0x78 => Instructions::LD_r8_r8(Registers8::A, Registers8::B),
            0x79 => Instructions::LD_r8_r8(Registers8::A, Registers8::C),
            0x7A => Instructions::LD_r8_r8(Registers8::A, Registers8::D),
            0x7B => Instructions::LD_r8_r8(Registers8::A, Registers8::E),
            0x7C => Instructions::LD_r8_r8(Registers8::A, Registers8::H),
            0x7D => Instructions::LD_r8_r8(Registers8::A, Registers8::L),
            0x7E => Instructions::LD_r8_HL(Registers8::A),
            0x7F => Instructions::LD_r8_r8(Registers8::A, Registers8::A),
            0x80 => Instructions::ADD_A_r8(Registers8::B),
            0x81 => Instructions::ADD_A_r8(Registers8::C),
            0x82 => Instructions::ADD_A_r8(Registers8::D),
            0x83 => Instructions::ADD_A_r8(Registers8::E),
            0x84 => Instructions::ADD_A_r8(Registers8::H),
            0x85 => Instructions::ADD_A_r8(Registers8::L),
            0x86 => Instructions::ADD_A_HL,
            0x87 => Instructions::ADD_A_r8(Registers8::A),
            0x88 => Instructions::ADC_A_r8(Registers8::B),
            0x89 => Instructions::ADC_A_r8(Registers8::C),
            0x8A => Instructions::ADC_A_r8(Registers8::D),
            0x8B => Instructions::ADC_A_r8(Registers8::E),
            0x8C => Instructions::ADC_A_r8(Registers8::H),
            0x8D => Instructions::ADC_A_r8(Registers8::L),
            0x8E => Instructions::ADC_A_HL,
            0x8F => Instructions::ADC_A_r8(Registers8::A),
            0x90 => Instructions::SUB_A_r8(Registers8::B),
            0x91 => Instructions::SUB_A_r8(Registers8::C),
            0x92 => Instructions::SUB_A_r8(Registers8::D),
            0x93 => Instructions::SUB_A_r8(Registers8::E),
            0x94 => Instructions::SUB_A_r8(Registers8::H),
            0x95 => Instructions::SUB_A_r8(Registers8::L),
            0x96 => Instructions::SUB_A_HL,
            0x97 => Instructions::SUB_A_r8(Registers8::A),
            0x98 => Instructions::SBC_A_r8(Registers8::B),
            0x99 => Instructions::SBC_A_r8(Registers8::C),
            0x9A => Instructions::SBC_A_r8(Registers8::D),
            0x9B => Instructions::SBC_A_r8(Registers8::E),
            0x9C => Instructions::SBC_A_r8(Registers8::H),
            0x9D => Instructions::SBC_A_r8(Registers8::L),
            0x9E => Instructions::SBC_A_HL,
            0x9F => Instructions::SBC_A_r8(Registers8::A),
            0xA0 => Instructions::AND_A_r8(Registers8::B),
            0xA1 => Instructions::AND_A_r8(Registers8::C),
            0xA2 => Instructions::AND_A_r8(Registers8::D),
            0xA3 => Instructions::AND_A_r8(Registers8::E),
            0xA4 => Instructions::AND_A_r8(Registers8::H),
            0xA5 => Instructions::AND_A_r8(Registers8::L),
            0xA6 => Instructions::AND_A_HL,
            0xA7 => Instructions::AND_A_r8(Registers8::A),
            0xA8 => Instructions::XOR_A_r8(Registers8::B),
            0xA9 => Instructions::XOR_A_r8(Registers8::C),
            0xAA => Instructions::XOR_A_r8(Registers8::D),
            0xAB => Instructions::XOR_A_r8(Registers8::E),
            0xAC => Instructions::XOR_A_r8(Registers8::H),
            0xAD => Instructions::XOR_A_r8(Registers8::L),
            0xAE => Instructions::XOR_A_HL,
            0xAF => Instructions::XOR_A_r8(Registers8::A),
            0xB0 => Instructions::OR_A_r8(Registers8::B),
            0xB1 => Instructions::OR_A_r8(Registers8::C),
            0xB2 => Instructions::OR_A_r8(Registers8::D),
            0xB3 => Instructions::OR_A_r8(Registers8::E),
            0xB4 => Instructions::OR_A_r8(Registers8::H),
            0xB5 => Instructions::OR_A_r8(Registers8::L),
            0xB6 => Instructions::OR_A_HL,
            0xB7 => Instructions::OR_A_r8(Registers8::A),
            0xB8 => Instructions::CP_A_r8(Registers8::B),
            0xB9 => Instructions::CP_A_r8(Registers8::C),
            0xBA => Instructions::CP_A_r8(Registers8::D),
            0xBB => Instructions::CP_A_r8(Registers8::E),
            0xBC => Instructions::CP_A_r8(Registers8::H),
            0xBD => Instructions::CP_A_r8(Registers8::L),
            0xBE => Instructions::CP_A_HL,
            0xBF => Instructions::CP_A_r8(Registers8::A),
            0xC0 => Instructions::RET_cc,
            0xC1 => Instructions::POP_r16(Registers16::BC),
            0xC2 => Instructions::JP_cc_n16,
            0xC3 => Instructions::JP_n16,
            0xC4 => Instructions::CALL_cc_n16,
            0xC5 => Instructions::PUSH_r16(Registers16::BC),
            0xC6 => Instructions::ADD_A_n8,
            0xC7 => Instructions::RST_vec,
            0xC8 => Instructions::RET_cc,
            0xC9 => Instructions::RET,
            0xCA => Instructions::JP_cc_n16,
            0xCB => Instructions::PREFIX,
            0xCC => Instructions::CALL_cc_n16,
            0xCD => Instructions::CALL_n16,
            0xCE => Instructions::ADC_A_n8,
            0xCF => Instructions::RST_vec,
            0xD0 => Instructions::RET_cc,
            0xD1 => Instructions::POP_r16(Registers16::DE),
            0xD2 => Instructions::JP_cc_n16,
            0xD3 => Instructions::NOP, // Unused opcode
            0xD4 => Instructions::CALL_cc_n16,
            0xD5 => Instructions::PUSH_r16(Registers16::DE),
            0xD6 => Instructions::SUB_A_n8,
            0xD7 => Instructions::RST_vec,
            0xD8 => Instructions::RET_cc,
            0xD9 => Instructions::RETI,
            0xDA => Instructions::JP_cc_n16,
            0xDB => Instructions::NONE,
            0xDC => Instructions::CALL_cc_n16,
            0xDD => Instructions::NONE,
            0xDE => Instructions::SBC_A_n8,
            0xDF => Instructions::RST_vec,
            0xE0 => Instructions::LDH_n16_A,
            0xE1 => Instructions::POP_r16(Registers16::HL),
            0xE2 => Instructions::LDH_C_A,
            0xE3 => Instructions::NONE,
            0xE4 => Instructions::NONE,
            0xE5 => Instructions::PUSH_r16(Registers16::HL),
            0xE6 => Instructions::AND_A_n8,
            0xE7 => Instructions::RST_vec,
            0xE8 => Instructions::ADD_SP_e8,
            0xE9 => Instructions::JP_HL,
            0xEA => Instructions::LD_n16_A,
            0xEB => Instructions::NONE,
            0xEC => Instructions::NONE,
            0xED => Instructions::NONE,
            0xEE => Instructions::XOR_A_n8,
            0xEF => Instructions::RST_vec,
            0xF0 => Instructions::LDH_A_n16,
            0xF1 => Instructions::POP_AF,
            0xF2 => Instructions::LDH_A_C,
            0xF3 => Instructions::DI,
            0xF4 => Instructions::NONE,
            0xF5 => Instructions::PUSH_AF,
            0xF6 => Instructions::OR_A_n8,
            0xF7 => Instructions::RST_vec,
            0xF8 => Instructions::LD_HL_SP_plus_e8,
            0xF9 => Instructions::LD_SP_HL,
            0xFA => Instructions::LD_A_n16,
            0xFB => Instructions::EI,
            0xFC => Instructions::NONE,
            0xFD => Instructions::NONE,
            0xFE => Instructions::CP_A_n8,
            0xFF => Instructions::RST_vec,
        }
    }

    pub fn get_instruction_prefixed(opcode: Opcode) -> Instructions {
        match opcode {
            0x00 => Instructions::RLC_r8(Registers8::B),
            0x01 => Instructions::RLC_r8(Registers8::C),
            0x02 => Instructions::RLC_r8(Registers8::D),
            0x03 => Instructions::RLC_r8(Registers8::E),
            0x04 => Instructions::RLC_r8(Registers8::H),
            0x05 => Instructions::RLC_r8(Registers8::L),
            0x06 => Instructions::RLC_HL,
            0x07 => Instructions::RLC_r8(Registers8::A),
            0x08 => Instructions::RRC_r8(Registers8::B),
            0x09 => Instructions::RRC_r8(Registers8::C),
            0x0A => Instructions::RRC_r8(Registers8::D),
            0x0B => Instructions::RRC_r8(Registers8::E),
            0x0C => Instructions::RRC_r8(Registers8::H),
            0x0D => Instructions::RRC_r8(Registers8::L),
            0x0E => Instructions::RRC_HL,
            0x0F => Instructions::RRC_r8(Registers8::A),
            0x10 => Instructions::RL_r8(Registers8::B),
            0x11 => Instructions::RL_r8(Registers8::C),
            0x12 => Instructions::RL_r8(Registers8::D),
            0x13 => Instructions::RL_r8(Registers8::E),
            0x14 => Instructions::RL_r8(Registers8::H),
            0x15 => Instructions::RL_r8(Registers8::L),
            0x16 => Instructions::RL_HL,
            0x17 => Instructions::RL_r8(Registers8::A),
            0x18 => Instructions::RR_r8(Registers8::B),
            0x19 => Instructions::RR_r8(Registers8::C),
            0x1A => Instructions::RR_r8(Registers8::D),
            0x1B => Instructions::RR_r8(Registers8::E),
            0x1C => Instructions::RR_r8(Registers8::H),
            0x1D => Instructions::RR_r8(Registers8::L),
            0x1E => Instructions::RR_HL,
            0x1F => Instructions::RR_r8(Registers8::A),
            0x20 => Instructions::SLA_r8(Registers8::B),
            0x21 => Instructions::SLA_r8(Registers8::C),
            0x22 => Instructions::SLA_r8(Registers8::D),
            0x23 => Instructions::SLA_r8(Registers8::E),
            0x24 => Instructions::SLA_r8(Registers8::H),
            0x25 => Instructions::SLA_r8(Registers8::L),
            0x26 => Instructions::SLA_HL,
            0x27 => Instructions::SLA_r8(Registers8::A),
            0x28 => Instructions::SRA_r8(Registers8::B),
            0x29 => Instructions::SRA_r8(Registers8::C),
            0x2A => Instructions::SRA_r8(Registers8::D),
            0x2B => Instructions::SRA_r8(Registers8::E),
            0x2C => Instructions::SRA_r8(Registers8::H),
            0x2D => Instructions::SRA_r8(Registers8::L),
            0x2E => Instructions::SRA_HL,
            0x2F => Instructions::SRA_r8(Registers8::A),
            0x30 => Instructions::SWAP_r8(Registers8::B),
            0x31 => Instructions::SWAP_r8(Registers8::C),
            0x32 => Instructions::SWAP_r8(Registers8::D),
            0x33 => Instructions::SWAP_r8(Registers8::E),
            0x34 => Instructions::SWAP_r8(Registers8::H),
            0x35 => Instructions::SWAP_r8(Registers8::L),
            0x36 => Instructions::SWAP_HL,
            0x37 => Instructions::SWAP_r8(Registers8::A),
            0x38 => Instructions::SRL_r8(Registers8::B),
            0x39 => Instructions::SRL_r8(Registers8::C),
            0x3A => Instructions::SRL_r8(Registers8::D),
            0x3B => Instructions::SRL_r8(Registers8::E),
            0x3C => Instructions::SRL_r8(Registers8::H),
            0x3D => Instructions::SRL_r8(Registers8::L),
            0x3E => Instructions::SRL_HL,
            0x3F => Instructions::SRL_r8(Registers8::A),
            0x40 => Instructions::BIT_u3_r8(Registers8::B),
            0x41 => Instructions::BIT_u3_r8(Registers8::C),
            0x42 => Instructions::BIT_u3_r8(Registers8::D),
            0x43 => Instructions::BIT_u3_r8(Registers8::E),
            0x44 => Instructions::BIT_u3_r8(Registers8::H),
            0x45 => Instructions::BIT_u3_r8(Registers8::L),
            0x46 => Instructions::BIT_u3_HL,
            0x47 => Instructions::BIT_u3_r8(Registers8::A),
            0x48 => Instructions::BIT_u3_r8(Registers8::B),
            0x49 => Instructions::BIT_u3_r8(Registers8::C),
            0x4A => Instructions::BIT_u3_r8(Registers8::D),
            0x4B => Instructions::BIT_u3_r8(Registers8::E),
            0x4C => Instructions::BIT_u3_r8(Registers8::H),
            0x4D => Instructions::BIT_u3_r8(Registers8::L),
            0x4E => Instructions::BIT_u3_HL,
            0x4F => Instructions::BIT_u3_r8(Registers8::A),
            0x50 => Instructions::BIT_u3_r8(Registers8::B),
            0x51 => Instructions::BIT_u3_r8(Registers8::C),
            0x52 => Instructions::BIT_u3_r8(Registers8::D),
            0x53 => Instructions::BIT_u3_r8(Registers8::E),
            0x54 => Instructions::BIT_u3_r8(Registers8::H),
            0x55 => Instructions::BIT_u3_r8(Registers8::L),
            0x56 => Instructions::BIT_u3_HL,
            0x57 => Instructions::BIT_u3_r8(Registers8::A),
            0x58 => Instructions::BIT_u3_r8(Registers8::B),
            0x59 => Instructions::BIT_u3_r8(Registers8::C),
            0x5A => Instructions::BIT_u3_r8(Registers8::D),
            0x5B => Instructions::BIT_u3_r8(Registers8::E),
            0x5C => Instructions::BIT_u3_r8(Registers8::H),
            0x5D => Instructions::BIT_u3_r8(Registers8::L),
            0x5E => Instructions::BIT_u3_HL,
            0x5F => Instructions::BIT_u3_r8(Registers8::A),
            0x60 => Instructions::BIT_u3_r8(Registers8::B),
            0x61 => Instructions::BIT_u3_r8(Registers8::C),
            0x62 => Instructions::BIT_u3_r8(Registers8::D),
            0x63 => Instructions::BIT_u3_r8(Registers8::E),
            0x64 => Instructions::BIT_u3_r8(Registers8::H),
            0x65 => Instructions::BIT_u3_r8(Registers8::L),
            0x66 => Instructions::BIT_u3_HL,
            0x67 => Instructions::BIT_u3_r8(Registers8::A),
            0x68 => Instructions::BIT_u3_r8(Registers8::B),
            0x69 => Instructions::BIT_u3_r8(Registers8::C),
            0x6A => Instructions::BIT_u3_r8(Registers8::D),
            0x6B => Instructions::BIT_u3_r8(Registers8::E),
            0x6C => Instructions::BIT_u3_r8(Registers8::H),
            0x6D => Instructions::BIT_u3_r8(Registers8::L),
            0x6E => Instructions::BIT_u3_HL,
            0x6F => Instructions::BIT_u3_r8(Registers8::A),
            0x70 => Instructions::RES_u3_r8(Registers8::B),
            0x71 => Instructions::RES_u3_r8(Registers8::C),
            0x72 => Instructions::RES_u3_r8(Registers8::D),
            0x73 => Instructions::RES_u3_r8(Registers8::E),
            0x74 => Instructions::RES_u3_r8(Registers8::H),
            0x75 => Instructions::RES_u3_r8(Registers8::L),
            0x76 => Instructions::RES_u3_HL,
            0x77 => Instructions::RES_u3_r8(Registers8::A),
            0x78 => Instructions::RES_u3_r8(Registers8::B),
            0x79 => Instructions::RES_u3_r8(Registers8::C),
            0x7A => Instructions::RES_u3_r8(Registers8::D),
            0x7B => Instructions::RES_u3_r8(Registers8::E),
            0x7C => Instructions::RES_u3_r8(Registers8::H),
            0x7D => Instructions::RES_u3_r8(Registers8::L),
            0x7E => Instructions::RES_u3_HL,
            0x7F => Instructions::RES_u3_r8(Registers8::A),
            0x80 => Instructions::SET_u3_r8(Registers8::B),
            0x81 => Instructions::SET_u3_r8(Registers8::C),
            0x82 => Instructions::SET_u3_r8(Registers8::D),
            0x83 => Instructions::SET_u3_r8(Registers8::E),
            0x84 => Instructions::SET_u3_r8(Registers8::H),
            0x85 => Instructions::SET_u3_r8(Registers8::L),
            0x86 => Instructions::SET_u3_HL,
            0x87 => Instructions::SET_u3_r8(Registers8::A),
            0x88 => Instructions::SET_u3_r8(Registers8::B),
            0x89 => Instructions::SET_u3_r8(Registers8::C),
            0x8A => Instructions::SET_u3_r8(Registers8::D),
            0x8B => Instructions::SET_u3_r8(Registers8::E),
            0x8C => Instructions::SET_u3_r8(Registers8::H),
            0x8D => Instructions::SET_u3_r8(Registers8::L),
            0x8E => Instructions::SET_u3_HL,
            0x8F => Instructions::SET_u3_r8(Registers8::A),
            0x90 => Instructions::SET_u3_r8(Registers8::B),
            0x91 => Instructions::SET_u3_r8(Registers8::C),
            0x92 => Instructions::SET_u3_r8(Registers8::D),
            0x93 => Instructions::SET_u3_r8(Registers8::E),
            0x94 => Instructions::SET_u3_r8(Registers8::H),
            0x95 => Instructions::SET_u3_r8(Registers8::L),
            0x96 => Instructions::SET_u3_HL,
            0x97 => Instructions::SET_u3_r8(Registers8::A),
            0x98 => Instructions::SET_u3_r8(Registers8::B),
            0x99 => Instructions::SET_u3_r8(Registers8::C),
            0x9A => Instructions::SET_u3_r8(Registers8::D),
            0x9B => Instructions::SET_u3_r8(Registers8::E),
            0x9C => Instructions::SET_u3_r8(Registers8::H),
            0x9D => Instructions::SET_u3_r8(Registers8::L),
            0x9E => Instructions::SET_u3_HL,
            0x9F => Instructions::SET_u3_r8(Registers8::A),
            0xA0 => Instructions::RES_u3_r8(Registers8::B),
            0xA1 => Instructions::RES_u3_r8(Registers8::C),
            0xA2 => Instructions::RES_u3_r8(Registers8::D),
            0xA3 => Instructions::RES_u3_r8(Registers8::E),
            0xA4 => Instructions::RES_u3_r8(Registers8::H),
            0xA5 => Instructions::RES_u3_r8(Registers8::L),
            0xA6 => Instructions::RES_u3_HL,
            0xA7 => Instructions::RES_u3_r8(Registers8::A),
            0xA8 => Instructions::RES_u3_r8(Registers8::B),
            0xA9 => Instructions::RES_u3_r8(Registers8::C),
            0xAA => Instructions::RES_u3_r8(Registers8::D),
            0xAB => Instructions::RES_u3_r8(Registers8::E),
            0xAC => Instructions::RES_u3_r8(Registers8::H),
            0xAD => Instructions::RES_u3_r8(Registers8::L),
            0xAE => Instructions::RES_u3_HL,
            0xAF => Instructions::RES_u3_r8(Registers8::A),
            0xB0 => Instructions::RES_u3_r8(Registers8::B),
            0xB1 => Instructions::RES_u3_r8(Registers8::C),
            0xB2 => Instructions::RES_u3_r8(Registers8::D),
            0xB3 => Instructions::RES_u3_r8(Registers8::E),
            0xB4 => Instructions::RES_u3_r8(Registers8::H),
            0xB5 => Instructions::RES_u3_r8(Registers8::L),
            0xB6 => Instructions::RES_u3_HL,
            0xB7 => Instructions::RES_u3_r8(Registers8::A),
            0xB8 => Instructions::RES_u3_r8(Registers8::B),
            0xB9 => Instructions::RES_u3_r8(Registers8::C),
            0xBA => Instructions::RES_u3_r8(Registers8::D),
            0xBB => Instructions::RES_u3_r8(Registers8::E),
            0xBC => Instructions::RES_u3_r8(Registers8::H),
            0xBD => Instructions::RES_u3_r8(Registers8::L),
            0xBE => Instructions::RES_u3_HL,
            0xBF => Instructions::RES_u3_r8(Registers8::A),
            0xC0 => Instructions::SET_u3_r8(Registers8::B),
            0xC1 => Instructions::SET_u3_r8(Registers8::C),
            0xC2 => Instructions::SET_u3_r8(Registers8::D),
            0xC3 => Instructions::SET_u3_r8(Registers8::E),
            0xC4 => Instructions::SET_u3_r8(Registers8::H),
            0xC5 => Instructions::SET_u3_r8(Registers8::L),
            0xC6 => Instructions::SET_u3_HL,
            0xC7 => Instructions::SET_u3_r8(Registers8::A),
            0xC8 => Instructions::SET_u3_r8(Registers8::B),
            0xC9 => Instructions::SET_u3_r8(Registers8::C),
            0xCA => Instructions::SET_u3_r8(Registers8::D),
            0xCB => Instructions::SET_u3_r8(Registers8::E),
            0xCC => Instructions::SET_u3_r8(Registers8::H),
            0xCD => Instructions::SET_u3_r8(Registers8::L),
            0xCE => Instructions::SET_u3_HL,
            0xCF => Instructions::SET_u3_r8(Registers8::A),
            0xD0 => Instructions::SET_u3_r8(Registers8::B),
            0xD1 => Instructions::SET_u3_r8(Registers8::C),
            0xD2 => Instructions::SET_u3_r8(Registers8::D),
            0xD3 => Instructions::SET_u3_r8(Registers8::E),
            0xD4 => Instructions::SET_u3_r8(Registers8::H),
            0xD5 => Instructions::SET_u3_r8(Registers8::L),
            0xD6 => Instructions::SET_u3_HL,
            0xD7 => Instructions::SET_u3_r8(Registers8::A),
            0xD8 => Instructions::SET_u3_r8(Registers8::B),
            0xD9 => Instructions::SET_u3_r8(Registers8::C),
            0xDA => Instructions::SET_u3_r8(Registers8::D),
            0xDB => Instructions::SET_u3_r8(Registers8::E),
            0xDC => Instructions::SET_u3_r8(Registers8::H),
            0xDD => Instructions::SET_u3_r8(Registers8::L),
            0xDE => Instructions::SET_u3_HL,
            0xDF => Instructions::SET_u3_r8(Registers8::A),
            0xE0 => Instructions::SET_u3_r8(Registers8::B),
            0xE1 => Instructions::SET_u3_r8(Registers8::C),
            0xE2 => Instructions::SET_u3_r8(Registers8::D),
            0xE3 => Instructions::SET_u3_r8(Registers8::E),
            0xE4 => Instructions::SET_u3_r8(Registers8::H),
            0xE5 => Instructions::SET_u3_r8(Registers8::L),
            0xE6 => Instructions::SET_u3_HL,
            0xE7 => Instructions::SET_u3_r8(Registers8::A),
            0xE8 => Instructions::SET_u3_r8(Registers8::B),
            0xE9 => Instructions::SET_u3_r8(Registers8::C),
            0xEA => Instructions::SET_u3_r8(Registers8::D),
            0xEB => Instructions::SET_u3_r8(Registers8::E),
            0xEC => Instructions::SET_u3_r8(Registers8::H),
            0xED => Instructions::SET_u3_r8(Registers8::L),
            0xEE => Instructions::SET_u3_HL,
            0xEF => Instructions::SET_u3_r8(Registers8::A),
            0xF0 => Instructions::RES_u3_r8(Registers8::B),
            0xF1 => Instructions::RES_u3_r8(Registers8::C),
            0xF2 => Instructions::RES_u3_r8(Registers8::D),
            0xF3 => Instructions::RES_u3_r8(Registers8::E),
            0xF4 => Instructions::RES_u3_r8(Registers8::H),
            0xF5 => Instructions::RES_u3_r8(Registers8::L),
            0xF6 => Instructions::RES_u3_HL,
            0xF7 => Instructions::RES_u3_r8(Registers8::A),
            0xF8 => Instructions::RES_u3_r8(Registers8::B),
            0xF9 => Instructions::RES_u3_r8(Registers8::C),
            0xFA => Instructions::RES_u3_r8(Registers8::D),
            0xFB => Instructions::RES_u3_r8(Registers8::E),
            0xFC => Instructions::RES_u3_r8(Registers8::H),
            0xFD => Instructions::RES_u3_r8(Registers8::L),
            0xFE => Instructions::RES_u3_HL,
            0xFF => Instructions::RES_u3_r8(Registers8::A),
        }
    }
}
